# Streamlit Secrets Configuration
# IMPORTANT: Replace with your actual Gemini API key for production

GEMINI_API_KEY = "YOUR_ACTUAL_GEMINI_API_KEY_HERE"

# Additional API keys and secrets can be added here
# These will be available via st.secrets in your Streamlit app

# For Streamlit Cloud deployment:
# 1. Do NOT commit this file to git
# 2. Add secrets through the Streamlit Cloud web interface instead