# Streamlit Secrets Configuration
# Add your Gemini API key here for production deployment
# This file should NOT be committed to git

# Example:
# GEMINI_API_KEY = "your-api-key-here"

# For local development, you can also use a .env file
# For Streamlit Cloud deployment, add secrets through the web interface